# Basic
title: Hukie's Blog
subtitle: A Blog About Android And Notes. 
welcome_message: Thank For Your Visit.
description: Learning To Be A Better Android Developer.
creator: <a href="http://onev.cat">@onevcat</a>

# url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: black

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
#nav:
    #- {title: About theme, description: Go to github of this theme, url: 'https://github.com/onevcat/vno-jekyll'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    #weibo: onevcat
    github: sununy
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail: whutzhanghu@163.com

# Google Analytics
#ga:
    # id: your_ga_id
    # host: your_host
